
export const INSERT_SUCCESS = 'INSERT_SUCCESS';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const NAME_SORT_ASCE = 'NAME_SORT_ASCE';
export const NAME_SORT_DSCE = 'NAME_SORT_DSCE';

export const AGE_SORT_ASCE = 'AGE_SORT_ASCE';
export const AGE_SORT_DSCE = 'AGE_SORT_DSCE';

export const SALARY_SORT_ASCE = 'SALARY_SORT_ASCE';
export const SALARY_SORT_DSCE = 'SALARY_SORT_DSCE';